// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var app, express, platform, port;

  express = require("express");

  platform = require("platform");

  app = express();

  require("dotenv").load();

  app.get("/:str", function(req, res) {
    var date, result, str;
    str = req.params.str;
    if (!isNaN(str)) {
      str = Number(str);
    }
    date = new Date(str);
    if (isNaN(Number(date))) {
      result = {
        unix: null,
        natural: null
      };
    } else {
      result = {
        unix: Number(date),
        natural: date.toLocaleDateString()
      };
    }
    return res.send(JSON.stringify(result));
  });

  port = process.env.PORT || 8080;

  app.listen(port, function() {
    return console.log("Server listening on port " + port + "...");
  });

}).call(this);
