// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var app, express, port;

  express = require("express");

  app = express();

  require("dotenv").load();

  app.get("/", function(req, res) {
    return res.send("append a unix- or natural date to the url");
  });

  app.get("/:str", function(req, res) {
    var date, result, resultStr, str;
    str = req.params.str;
    if (!isNaN(str)) {
      str = Number(str);
    }
    date = new Date(str);
    if (isNaN(Number(date))) {
      result = {
        unix: null,
        natural: null
      };
    } else {
      result = {
        unix: Number(date),
        natural: date.toLocaleDateString()
      };
    }
    resultStr = JSON.stringify(result);
    console.log(str + " => " + resultStr);
    return res.send(resultStr);
  });

  port = process.env.PORT || 8080;

  app.listen(port, function() {
    return console.log("Server listening on port " + port + "...");
  });

}).call(this);
